/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
	sidebar: [
		{
			type: "doc",
			label: "Primeiros passos",
			id: "getting-started",
		},
		{
			type: "category",
			label: "Ferramentas",
			items: [
				"developer-tools/overview",
				"developer-tools/templates",
				"developer-tools/nimbus",
				"developer-tools/nexo",
				"developer-tools/nuvemshop-api",
			],
		},
		{
			type: "category",
			label: "Aplicativos",
			items: [
				"applications/overview",
				"applications/authentication",
				"applications/native",
				"applications/standalone",
				"applications/guidelines",
				{
					type: "category",
					label: "Nube SDK",
					items: [
						"applications/nube-sdk/overview",
						"applications/nube-sdk/getting-started",
						"applications/nube-sdk/devtools",
						"applications/nube-sdk/script-structure",
						"applications/nube-sdk/styling",
						"applications/nube-sdk/state",
						"applications/nube-sdk/events",
						"applications/nube-sdk/browser-apis",
						"applications/nube-sdk/migration-guide",
					{
						type: "category",
						label: "Components",
						items: [
							"applications/nube-sdk/components/accordion",
							"applications/nube-sdk/components/box",
							"applications/nube-sdk/components/button",
							"applications/nube-sdk/components/checkbox",
							"applications/nube-sdk/components/column",
							"applications/nube-sdk/components/field",
							"applications/nube-sdk/components/fragment",
							"applications/nube-sdk/components/image",
							"applications/nube-sdk/components/icon",
							"applications/nube-sdk/components/iframe",
							"applications/nube-sdk/components/overview",
							"applications/nube-sdk/components/row",
							"applications/nube-sdk/components/select",
							"applications/nube-sdk/components/sidescroll",
							"applications/nube-sdk/components/svg",
							"applications/nube-sdk/components/text",
							"applications/nube-sdk/components/link",
							"applications/nube-sdk/components/markdown",
							"applications/nube-sdk/components/textarea",
							"applications/nube-sdk/components/toast",
						],
					},
				{
					type: "category",
					label: "UI Slots",
					items: [
						"applications/nube-sdk/slots/overview",
						"applications/nube-sdk/slots/checkout-slots",
						"applications/nube-sdk/slots/storefront-slots",
					],
				},
				{
					type: "category",
					label: "Examples",
					items: [
						"applications/nube-sdk/examples/overview",
						{
							type: "category",
							label: "Common Patterns",
							items: [
								"applications/nube-sdk/examples/carousel",
								"applications/nube-sdk/examples/banner",
								"applications/nube-sdk/examples/faq",
								"applications/nube-sdk/examples/extra-info-tags",
								"applications/nube-sdk/examples/extra-info-product-list",
								"applications/nube-sdk/examples/modal-popup",
							],
						},
					],
				},
				],
			},
		],
	},
	{
		type: "category",
		label: "Diretrizes de design",
			items: [
				"design-guidelines/overview",
				"design-guidelines/template-usage",
				"design-guidelines/component-usage",
				"design-guidelines/concept-usage",
				"design-guidelines/ux-writing-usage",
			],
		},
		{
			type: "category",
			label: "Homologação",
			items: [
				"homologation/overview",
				"homologation/assync",
				"homologation/sync",
				"homologation/guidelines",
				"homologation/requirements",
			],
		},
		{
<<<<<<< HEAD
			type: "category", 
			label: "Publicação do App",
			items: [
				"publication/overview",
				"publication/requirements",
				"publication/publications",
				"homologation/checklist",
=======
			type: "category",
			label: "Publicação de Apps",
			items: [
			  "publication-apps/overview",
			  "publication-apps/requirements",
			  "publication-apps/publications",
			  "publication-apps/checklist",
>>>>>>> 5007711 (docs: add publication apps documentation)
			],
		},
		{
			type: "doc",
			label: "Guia de integração de ERPs",
			id: "erp-guide/overview",
		},
	],

	// custom sidebar used until we release the nube sdk to the public
	nube_sdk_sidebar: [
		{
			type: "category",
			label: "Nube SDK",
			items: [
				"applications/nube-sdk/overview",
				"applications/nube-sdk/getting-started",
				"applications/nube-sdk/devtools",
				"applications/nube-sdk/script-structure",
				"applications/nube-sdk/styling",
				"applications/nube-sdk/state",
				"applications/nube-sdk/events",
				"applications/nube-sdk/browser-apis",
				{
					type: "category",
					label: "Components",
					items: [
						"applications/nube-sdk/components/overview",
						"applications/nube-sdk/components/accordion",
						"applications/nube-sdk/components/box",
						"applications/nube-sdk/components/button",
						"applications/nube-sdk/components/checkbox",
						"applications/nube-sdk/components/column",
						"applications/nube-sdk/components/field",
						"applications/nube-sdk/components/fragment",
						"applications/nube-sdk/components/icon",
						"applications/nube-sdk/components/iframe",
						"applications/nube-sdk/components/image",
						"applications/nube-sdk/components/progress",
						"applications/nube-sdk/components/row",
						"applications/nube-sdk/components/select",
						"applications/nube-sdk/components/sidescroll",
						"applications/nube-sdk/components/svg",
						"applications/nube-sdk/components/text",
						"applications/nube-sdk/components/link",
						"applications/nube-sdk/components/markdown",
						"applications/nube-sdk/components/textarea",
						"applications/nube-sdk/components/toast",
					],
				},
			{
				type: "category",
				label: "UI Slots",
				items: [
					"applications/nube-sdk/slots/overview",
					"applications/nube-sdk/slots/checkout-slots",
					"applications/nube-sdk/slots/storefront-slots",
				],
			},
	{
		type: "category",
		label: "Examples",
		items: [
			"applications/nube-sdk/examples/overview",
			{
		type: "category",
		label: "Common Patterns",
		items: [
			"applications/nube-sdk/examples/carousel",
			"applications/nube-sdk/examples/banner",
			"applications/nube-sdk/examples/faq",
			"applications/nube-sdk/examples/extra-info-tags",
			"applications/nube-sdk/examples/extra-info-product-list",
			"applications/nube-sdk/examples/modal-popup",
		],
	},
		],
	},
],
},
],
};

module.exports = sidebars;
