/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
	sidebar: [
		{
			type: "doc",
			label: "Primeiros passos",
			id: "getting-started",
		},
		{
			type: "category",
			label: "Ferramentas",
			items: [
				"developer-tools/overview",
				"developer-tools/templates",
				"developer-tools/nimbus",
				"developer-tools/nexo",
				"developer-tools/nuvemshop-api",
			],
		},
		{
			type: "category",
			label: "Aplicativos",
			items: [
				"applications/overview",
				"applications/authentication",
				"applications/native",
				"applications/standalone",
				"applications/guidelines",
				{
					type: "category",
					label: "Nube SDK",
					items: [
						"applications/nube-sdk/overview",
						"applications/nube-sdk/getting-started",
						"applications/nube-sdk/devtools",
						"applications/nube-sdk/script-structure",
						"applications/nube-sdk/styling",
						{
							type: "category",
							label: "State",
							link: {
								type: "doc",
								id: "applications/nube-sdk/state/overview",
							},
							items: [
								"applications/nube-sdk/state/cart",
								"applications/nube-sdk/state/order",
								"applications/nube-sdk/state/location",
								"applications/nube-sdk/state/store-and-config",
								"applications/nube-sdk/state/shipping",
								"applications/nube-sdk/state/customer",
								"applications/nube-sdk/state/payment",
								"applications/nube-sdk/state/ui-and-session",
							],
						},
						{
							type: "category",
							label: "Events",
							link: {
								type: "doc",
								id: "applications/nube-sdk/events/overview",
							},
							items: [
								"applications/nube-sdk/events/page-and-lifecycle",
								"applications/nube-sdk/events/cart",
								"applications/nube-sdk/events/order",
								"applications/nube-sdk/events/coupon",
								"applications/nube-sdk/events/shipping",
								"applications/nube-sdk/events/customer-and-payment",
								"applications/nube-sdk/events/ui-and-custom",
							],
						},
						"applications/nube-sdk/browser-apis",
					{
						type: "category",
						label: "Migration Guide",
						link: {
							type: "doc",
							id: "applications/nube-sdk/migration-guide",
						},
						items: [
							{ type: "link", label: "1. Entry point", href: "/docs/applications/nube-sdk/migration-guide#1-entry-point" },
							{ type: "link", label: "2. Page or route changes", href: "/docs/applications/nube-sdk/migration-guide#2-reacting-to-page-or-route-changes" },
							{ type: "link", label: "3. User interactions", href: "/docs/applications/nube-sdk/migration-guide#3-listening-to-user-interactions" },
							{ type: "link", label: "4. Injecting UI", href: "/docs/applications/nube-sdk/migration-guide#4-injecting-ui-into-the-page" },
							{ type: "link", label: "5. Dynamic UI & state", href: "/docs/applications/nube-sdk/migration-guide#5-rendering-dynamic-ui-based-on-state" },
							{ type: "link", label: "6. Styling", href: "/docs/applications/nube-sdk/migration-guide#6-styling" },
							{ type: "link", label: "7. Cart data", href: "/docs/applications/nube-sdk/migration-guide#7-reading-and-reacting-to-cart-data" },
							{ type: "link", label: "8. Cart validation", href: "/docs/applications/nube-sdk/migration-guide#8-validating-the-cart--blocking-checkout" },
							{ type: "link", label: "9. HTTP requests", href: "/docs/applications/nube-sdk/migration-guide#9-making-http-requests" },
							{ type: "link", label: "10. localStorage", href: "/docs/applications/nube-sdk/migration-guide#10-using-localstorage--sessionstorage" },
							{ type: "link", label: "11. Navigation", href: "/docs/applications/nube-sdk/migration-guide#11-navigating-programmatically" },
							{ type: "link", label: "12. Shipping & payment", href: "/docs/applications/nube-sdk/migration-guide#12-reacting-to-shipping-and-payment-changes" },
							{ type: "link", label: "13. Customer data", href: "/docs/applications/nube-sdk/migration-guide#13-reacting-to-customer-data" },
							{ type: "link", label: "14. Adding to cart", href: "/docs/applications/nube-sdk/migration-guide#14-adding-items-to-the-cart" },
							{ type: "link", label: "15. Order tracking", href: "/docs/applications/nube-sdk/migration-guide#15-order-tracking-checkout-success-page" },
							{ type: "link", label: "What you can't do", href: "/docs/applications/nube-sdk/migration-guide#what-you-cant-do-in-nubesdk" },
							{ type: "link", label: "Migration checklist", href: "/docs/applications/nube-sdk/migration-guide#migration-checklist" },
							{ type: "link", label: "Useful resources", href: "/docs/applications/nube-sdk/migration-guide#useful-resources" },
						],
					},
					{
						type: "category",
						label: "Components",
						link: {
							type: "doc",
							id: "applications/nube-sdk/components/overview",
						},
						items: [
							"applications/nube-sdk/components/accordion",
							"applications/nube-sdk/components/box",
							"applications/nube-sdk/components/button",
							"applications/nube-sdk/components/checkbox",
							"applications/nube-sdk/components/column",
							"applications/nube-sdk/components/field",
							"applications/nube-sdk/components/fragment",
							"applications/nube-sdk/components/image",
							"applications/nube-sdk/components/icon",
							"applications/nube-sdk/components/iframe",
							"applications/nube-sdk/components/row",
							"applications/nube-sdk/components/select",
							"applications/nube-sdk/components/sidescroll",
							"applications/nube-sdk/components/svg",
							"applications/nube-sdk/components/text",
							"applications/nube-sdk/components/link",
							"applications/nube-sdk/components/markdown",
							"applications/nube-sdk/components/textarea",
							"applications/nube-sdk/components/toast",
						],
					},
				{
					type: "category",
					label: "UI Slots",
					link: {
						type: "doc",
						id: "applications/nube-sdk/slots/overview",
					},
					items: [
						"applications/nube-sdk/slots/checkout-slots",
						"applications/nube-sdk/slots/storefront-slots",
					],
				},
				{
					type: "category",
					label: "Examples",
					link: {
						type: "doc",
						id: "applications/nube-sdk/examples/overview",
					},
					items: [
						{
							type: "category",
							label: "Common Patterns",
							items: [
								"applications/nube-sdk/examples/carousel",
								"applications/nube-sdk/examples/banner",
								"applications/nube-sdk/examples/faq",
								"applications/nube-sdk/examples/extra-info-tags",
								"applications/nube-sdk/examples/extra-info-product-list",
								"applications/nube-sdk/examples/modal-popup",
							],
						},
					],
				},
				],
			},
		],
	},
	{
		type: "category",
		label: "Diretrizes de design",
			items: [
				"design-guidelines/overview",
				"design-guidelines/template-usage",
				"design-guidelines/component-usage",
				"design-guidelines/concept-usage",
				"design-guidelines/ux-writing-usage",
			],
		},
		{
			type: "category",
			label: "Homologação",
			items: [
				"homologation/overview",
				"homologation/assync",
				"homologation/sync",
				"homologation/guidelines",
				"homologation/requirements",
				"homologation/publication",
				"homologation/checklist",
			],
		},
		{
			type: "doc",
			label: "Guia de integração de ERPs",
			id: "erp-guide/overview",
		},
	],

	// custom sidebar used until we release the nube sdk to the public
	nube_sdk_sidebar: [
		{
			type: "category",
			label: "Nube SDK",
			items: [
				"applications/nube-sdk/overview",
				"applications/nube-sdk/getting-started",
				"applications/nube-sdk/devtools",
				"applications/nube-sdk/script-structure",
				"applications/nube-sdk/styling",
			{
				type: "category",
				label: "State",
				link: {
					type: "doc",
					id: "applications/nube-sdk/state/overview",
				},
				items: [
					"applications/nube-sdk/state/cart",
					"applications/nube-sdk/state/order",
					"applications/nube-sdk/state/location",
					"applications/nube-sdk/state/store-and-config",
					"applications/nube-sdk/state/shipping",
					"applications/nube-sdk/state/customer",
					"applications/nube-sdk/state/payment",
					"applications/nube-sdk/state/ui-and-session",
				],
			},
		{
				type: "category",
				label: "Events",
				link: {
					type: "doc",
					id: "applications/nube-sdk/events/overview",
				},
				items: [
					"applications/nube-sdk/events/page-and-lifecycle",
					"applications/nube-sdk/events/cart",
					"applications/nube-sdk/events/order",
					"applications/nube-sdk/events/coupon",
					"applications/nube-sdk/events/shipping",
					"applications/nube-sdk/events/customer-and-payment",
					"applications/nube-sdk/events/ui-and-custom",
				],
			},
	"applications/nube-sdk/browser-apis",
	{
		type: "category",
		label: "Migration Guide",
		link: {
			type: "doc",
			id: "applications/nube-sdk/migration-guide",
		},
		items: [
			{ type: "link", label: "1. Entry point", href: "/docs/applications/nube-sdk/migration-guide#1-entry-point" },
			{ type: "link", label: "2. Page or route changes", href: "/docs/applications/nube-sdk/migration-guide#2-reacting-to-page-or-route-changes" },
			{ type: "link", label: "3. User interactions", href: "/docs/applications/nube-sdk/migration-guide#3-listening-to-user-interactions" },
			{ type: "link", label: "4. Injecting UI", href: "/docs/applications/nube-sdk/migration-guide#4-injecting-ui-into-the-page" },
			{ type: "link", label: "5. Dynamic UI & state", href: "/docs/applications/nube-sdk/migration-guide#5-rendering-dynamic-ui-based-on-state" },
			{ type: "link", label: "6. Styling", href: "/docs/applications/nube-sdk/migration-guide#6-styling" },
			{ type: "link", label: "7. Cart data", href: "/docs/applications/nube-sdk/migration-guide#7-reading-and-reacting-to-cart-data" },
			{ type: "link", label: "8. Cart validation", href: "/docs/applications/nube-sdk/migration-guide#8-validating-the-cart--blocking-checkout" },
			{ type: "link", label: "9. HTTP requests", href: "/docs/applications/nube-sdk/migration-guide#9-making-http-requests" },
			{ type: "link", label: "10. localStorage", href: "/docs/applications/nube-sdk/migration-guide#10-using-localstorage--sessionstorage" },
			{ type: "link", label: "11. Navigation", href: "/docs/applications/nube-sdk/migration-guide#11-navigating-programmatically" },
			{ type: "link", label: "12. Shipping & payment", href: "/docs/applications/nube-sdk/migration-guide#12-reacting-to-shipping-and-payment-changes" },
			{ type: "link", label: "13. Customer data", href: "/docs/applications/nube-sdk/migration-guide#13-reacting-to-customer-data" },
			{ type: "link", label: "14. Adding to cart", href: "/docs/applications/nube-sdk/migration-guide#14-adding-items-to-the-cart" },
			{ type: "link", label: "15. Order tracking", href: "/docs/applications/nube-sdk/migration-guide#15-order-tracking-checkout-success-page" },
		{ type: "link", label: "What you can't do", href: "/docs/applications/nube-sdk/migration-guide#what-you-cant-do-in-nubesdk" },
		{ type: "link", label: "Migration checklist", href: "/docs/applications/nube-sdk/migration-guide#migration-checklist" },
		{ type: "link", label: "Useful resources", href: "/docs/applications/nube-sdk/migration-guide#useful-resources" },
		],
	},
		{
			type: "category",
			label: "Components",
				link: {
					type: "doc",
					id: "applications/nube-sdk/components/overview",
				},
				items: [
					"applications/nube-sdk/components/accordion",
						"applications/nube-sdk/components/box",
						"applications/nube-sdk/components/button",
						"applications/nube-sdk/components/checkbox",
						"applications/nube-sdk/components/column",
						"applications/nube-sdk/components/field",
						"applications/nube-sdk/components/fragment",
						"applications/nube-sdk/components/icon",
						"applications/nube-sdk/components/iframe",
						"applications/nube-sdk/components/image",
						"applications/nube-sdk/components/progress",
						"applications/nube-sdk/components/row",
						"applications/nube-sdk/components/select",
						"applications/nube-sdk/components/sidescroll",
						"applications/nube-sdk/components/svg",
						"applications/nube-sdk/components/text",
						"applications/nube-sdk/components/link",
						"applications/nube-sdk/components/markdown",
						"applications/nube-sdk/components/textarea",
						"applications/nube-sdk/components/toast",
					],
				},
		{
			type: "category",
			label: "UI Slots",
			link: {
				type: "doc",
				id: "applications/nube-sdk/slots/overview",
			},
			items: [
				"applications/nube-sdk/slots/checkout-slots",
				"applications/nube-sdk/slots/storefront-slots",
			],
		},
	{
		type: "category",
		label: "Examples",
		link: {
			type: "doc",
			id: "applications/nube-sdk/examples/overview",
		},
		items: [
			{
		type: "category",
		label: "Common Patterns",
		items: [
			"applications/nube-sdk/examples/carousel",
			"applications/nube-sdk/examples/banner",
			"applications/nube-sdk/examples/faq",
			"applications/nube-sdk/examples/extra-info-tags",
			"applications/nube-sdk/examples/extra-info-product-list",
			"applications/nube-sdk/examples/modal-popup",
		],
	},
		],
	},
],
},
],
};

module.exports = sidebars;
