/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  sidebar: [
    {
      type: "category",
      label: "Getting started",
      items: [
        "getting-started/overview",
        "getting-started/create-an-app",
        "getting-started/build-an-app",
      ],
    },
    {
      type: "doc",
      label: "API Nuvemshop",
      id: "api-nuvemshop",
    },
    {
      type: "doc",
      label: "Developer tools",
      id: "developer-tools",
    },
    {
      type: "doc",
      label: "Best practices",
      id: "best-practices",
    },
    {
      type: "doc",
      label: "Design guidelines",
      id: "design-guidelines",
    },
    {
      type: "doc",
      label: "Enhanced applications",
      id: "enhanced-applications",
    },
    {
      type: "doc",
      label: "Standalone applications",
      id: "standalone-applications",
    },
    {
      type: "doc",
      label: "Homologation",
      id: "homologation",
    },
  ],
};

module.exports = sidebars;
